package dev.copperbench.generator;

import com.google.gson.JsonObject;
import dev.copperbench.core.workspace.WorkspaceState;
import dev.copperbench.core.workspace.WorkspaceState.Element;
import dev.copperbench.generator.fabric.Fabric1211Generator;
import dev.copperbench.generator.fabric.Fabric1211GoldenWorkspace;
import dev.copperbench.generator.neoforge.NeoForge1211Generator;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class Stage17ProcedureTaskValidationTest {
    @TempDir Path root;
    @ParameterizedTest
    @ValueSource(strings = {"fabric-1.20.1", "fabric-1.21.1", "fabric-26.1.2", "fabric-26.2",
            "neoforge-1.20.1", "neoforge-1.21.1", "neoforge-26.1.2", "neoforge-26.2"})
    void realBodiesDoNotRequireLegacyMessageAndCannotFallBackToPlaceholderCode(String track) throws Exception {
        WorkspaceState base = Fabric1211GoldenWorkspace.create();
        var generatorInfo = base.generator(); generatorInfo.addProperty("id", track);
        generatorInfo.addProperty("loader", track.startsWith("fabric") ? "fabric" : "neoforge");
        generatorInfo.addProperty("minecraftVersion", track.substring(track.indexOf('-') + 1));
        WorkspaceState state = base.withGenerator(generatorInfo);
        Element procedure = state.elements().stream().filter(e -> e.type().equals("procedure")).findFirst().orElseThrow();
        JsonObject values = new JsonObject(); JsonObject fields = new JsonObject();
        fields.addProperty("procedurexml", "<xml><block type=\"event_trigger\"><field name=\"trigger\">no_ext_trigger</field></block></xml>");
        values.add("fields", fields);
        state.replaceElement(new Element(procedure.id(), procedure.type(), procedure.name(), procedure.displayName(), procedure.state(), procedure.ownership(), procedure.updatedAt(), values));
        boolean fabric = track.startsWith("fabric");
        var fabricProfile = java.util.List.of(Fabric1211Generator.Profile.FABRIC_1201, Fabric1211Generator.Profile.FABRIC_1211,
                Fabric1211Generator.Profile.FABRIC_261, Fabric1211Generator.Profile.FABRIC_262).stream()
                .filter(p -> p.generatorId().equals(track)).findFirst().orElse(Fabric1211Generator.Profile.FABRIC_1211);
        var neoProfile = java.util.List.of(NeoForge1211Generator.Profile.NEOFORGE_1201, NeoForge1211Generator.Profile.NEOFORGE_1211,
                NeoForge1211Generator.Profile.NEOFORGE_261, NeoForge1211Generator.Profile.NEOFORGE_262).stream()
                .filter(p -> p.generatorId().equals(track)).findFirst().orElse(NeoForge1211Generator.Profile.NEOFORGE_1211);
        var fabricGenerator = new Fabric1211Generator(Path.of("."), fabricProfile);
        var neoGenerator = new NeoForge1211Generator(Path.of("."), neoProfile);
        assertTrue((fabric ? fabricGenerator.validate(state) : neoGenerator.validate(state)).isEmpty());
        Element validProcedure = state.element(procedure.id());
        JsonObject invalidValues = new JsonObject();
        invalidValues.addProperty("procedurexml", "<xml><block type=\"event_trigger\"><field name=\"trigger\">no_ext_trigger</field><next>"
                + "<block type=\"return_number\"><value name=\"VALUE\"><block type=\"text\"><field name=\"TEXT\">invalid</field>"
                + "</block></value></block></next></block></xml>");
        state.replaceElement(new Element(procedure.id(), procedure.type(), procedure.name(), procedure.displayName(), procedure.state(), procedure.ownership(), procedure.updatedAt(), invalidValues));
        assertTrue(fabric ? fabricGenerator.validate(state).stream().anyMatch(issue -> issue.code().equals("PROCEDURE_RETURN_TYPE_MISMATCH"))
                : neoGenerator.validate(state).stream().anyMatch(issue -> issue.code().equals("PROCEDURE_RETURN_TYPE_MISMATCH")));
        state.replaceElement(validProcedure);
        var failure = assertThrows(IllegalArgumentException.class, () -> {
            if (fabric) fabricGenerator.generate(root, state); else neoGenerator.generate(root, state);
        });
        assertTrue(failure.getMessage().contains("plugin generator"), failure.getMessage());
        assertFalse(Files.exists(root.resolve("src")), "Rejected fallback must not generate a placeholder source");
        Files.writeString(root.resolve("trial.mcreator"), "{}");
        Path existing = root.resolve("src/main/java/PreservedProcedure.java"); Files.createDirectories(existing.getParent());
        String body = "// Already generated by the plugin; preserve the real Procedure body";
        Files.writeString(existing, body);
        if (fabric) fabricGenerator.generate(root, state); else neoGenerator.generate(root, state);
        assertEquals(body, Files.readString(existing));
    }
}
