$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$gate = Get-Content -LiteralPath (Join-Path $root 'scripts\Invoke-Stage15WindowsProductRegressionGuestGate.ps1') -Raw
$guestScriptMatch = [regex]::Match($gate, "(?s)\$guestScript = @'\r?\n(.*?)\r?\n'@")
if (-not $guestScriptMatch.Success) { throw 'Stage 15 Windows gate must contain an embedded guest acceptance script.' }
$guestGate = $guestScriptMatch.Groups[1].Value

function Assert-Match([string]$Text, [string]$Pattern, [string]$Message) {
	if ($Text -notmatch $Pattern) { throw $Message }
}

function Assert-NotMatch([string]$Text, [string]$Pattern, [string]$Message) {
	if ($Text -match $Pattern) { throw $Message }
}

Assert-Match $gate 'Invoke-Stage14SourceIntegrityGuestGate\.ps1' 'Stage 15 Windows gate must reuse the real installed-product Stage 14 baseline.'
Assert-Match $gate 'p0fabricfinald0d' 'Stage 15 Windows gate must bind the preserved Fabric 26.1.2 acceptance workspace.'
Assert-Match $gate 'Get-FileHash.+SHA256' 'Stage 15 Windows gate must bind the exact installer SHA-256.'
Assert-Match $gate 'candidateSourceHead' 'Stage 15 Windows gate must bind source HEAD.'
Assert-Match $gate 'candidateSourceDeltaSha256' 'Stage 15 Windows gate must bind source-delta SHA-256.'
Assert-Match $gate 'WM_NCHITTEST|0x0084' 'The supplemental gate must map the installed custom title bar through native WM_NCHITTEST as in the historical P0 acceptance.'
Assert-Match $gate 'HTCLIENT' 'Resolved title-bar action centers must be verified as real client controls.'
Assert-Match $gate 'Resolve-TitlebarNativeAction' 'The gate must resolve title-bar controls from the production native hit-test regions rather than reuse a fixed coordinate.'
Assert-Match $guestGate 'function Get-TitlebarClientRegions' 'Native title-bar client-region discovery must be defined inside the guest acceptance script.'
Assert-Match $guestGate 'function Resolve-TitlebarNativeAction' 'Native title-bar action resolution must be defined inside the guest acceptance script, not only in the host wrapper scope.'
Assert-Match $guestGate 'function Invoke-TitlebarHitTestAction' 'Native title-bar invocation must be defined inside the guest acceptance script where build/runClient call it.'
Assert-Match $guestGate 'function Invoke-McpUiButton' 'MCP UI automation must be defined inside the guest acceptance script that owns the interactive desktop session.'
Assert-Match $guestGate "'build' \{ 1 \}" 'The build action must bind to the second center client region reported by the production title bar.'
Assert-Match $guestGate "'runClient' \{ 2 \}" 'The runClient action must bind to the third center client region reported by the production title bar.'
Assert-Match $guestGate 'ReadWindowRect' 'The gate must derive the scan from the actual installed product window geometry.'
Assert-Match $guestGate 'regions\.Count -ge 6' 'The gate must require the complete six-action center cluster before resolving build or runClient.'
Assert-Match $guestGate "resolution='native-titlebar-client-region-order'" 'Evidence must record that action coordinates came from native title-bar client regions.'
Assert-Match $guestGate "resolutionRoot='wm-nchittest-window-chrome-snapshot'" 'Evidence must bind action resolution to the native WindowChromeSnapshot hit-test path.'
Assert-Match $gate 'Invoke-TitlebarHitTestAction \$hwnd ''build''' 'Installed Fabric 26.1.2 build must start from the real native-hit-test title-bar build control.'
Assert-Match $gate 'Invoke-TitlebarHitTestAction \$hwnd ''runClient''' 'Interactive runClient must start from the real native-hit-test title-bar test-client control.'
Assert-Match $guestGate "Add-Step 'titlebar_build_click'" 'Build click coordinates must be written to evidence before waiting for the Gradle process.'
Assert-Match $guestGate "Add-Step 'titlebar_run_client_click'" 'Run Client click coordinates must be written to evidence before waiting for Minecraft.'
Assert-Match $gate 'ClickScreenPoint' 'The gate must deliver a real mouse click to the resolved native title-bar client region.'
Assert-NotMatch $gate '521\s*,\s*55' 'The gate must not hard-code the historical P0 click coordinate.'
Assert-Match $gate "Wait-NewGradleCommand 'build'" 'The build gate must observe the actual Gradle command spawned by the UI action.'
Assert-Match $gate "Wait-NewGradleCommand 'runClient'" 'The lifecycle gate must observe the actual runClient Gradle command spawned by the UI action.'
Assert-Match $gate 'function Test-ProcessDescendsFrom' 'The gate must bind observed Gradle commands to the active installed Copperbench process tree.'
Assert-Match $gate 'Test-ProcessDescendsFrom \$_ \$ExpectedParentProcessId' 'Observed Gradle commands must descend from the active installed Copperbench javaw process.'
Assert-Match $gate 'gradleParentProcessId' 'Acceptance evidence must record the observed Gradle process parent identity.'
Assert-Match $gate 'OpenProcess\(0x00101000' 'The gate must retain a native query/synchronize handle for observed Gradle commands before they exit.'
Assert-Match $gate 'GetExitCodeProcess' 'The gate must read real native exit codes for Gradle commands it did not spawn itself.'
Assert-Match $gate 'exitCodeObserved=\$true' 'The build evidence must require an observed native Gradle exit code.'
Assert-Match $gate 'gradleExitCodeObserved=\$true' 'The runClient evidence must require an observed native Gradle exit code after normal Minecraft close.'
Assert-Match $gate "desktopJavaBefore = Get-ProcessIdsByName 'javaw\.exe'" 'The gate must snapshot pre-existing javaw processes so single-instance JVM reuse is explicit in evidence.'
Assert-Match $gate 'function Get-InstalledWorkspaceWindows' 'The gate must enumerate real installed-product top-level workspace windows.'
Assert-Match $gate 'workspaceWindowsBefore' 'The gate must snapshot pre-existing workspace HWNDs before forwarding a new workspace launch.'
Assert-Match $gate 'handle -notin \$workspaceWindowsBefore' 'The acceptance workspace must bind to a newly created top-level window even when the JVM is reused.'
Assert-Match $gate 'freshWorkspaceWindow=\$true' 'Evidence must record that the acceptance frame is a fresh workspace window.'
Assert-Match $gate 'desktopProcessReused=' 'Evidence must record whether the single-instance desktop JVM was reused.'
Assert-Match $gate 'Wait-BundledRuntimeJava' 'The Fabric 26.1.2 build gate must verify the installed bundled Java 25 runtime even when Gradle reuses an already-running daemon.'
Assert-Match $gate 'bundledRuntimeProcessReused' 'Evidence must state whether the observed bundled Java 25 process was newly started or an existing Gradle daemon.'
Assert-Match $gate 'build\\libs' 'The installed 26.1.2 build must produce a real jar artifact.'
Assert-Match $gate 'buildFailureDiagnostic' 'A failed UI build must capture a bounded direct Gradle diagnostic replay instead of hiding the real failure.'
Assert-Match $gate 'RedirectStandardOutput' 'The direct build diagnostic must capture native stdout without turning javac warnings into terminating PowerShell errors.'
Assert-Match $gate 'RedirectStandardError' 'The direct build diagnostic must capture native stderr without turning javac warnings into terminating PowerShell errors.'
Assert-Match $gate 'Select-Object -Last 160' 'Failure diagnostic output must be bounded before it is persisted into evidence.'
Assert-Match $gate '--no-daemon' 'The runClient gate must retain the historical installed-product no-daemon lifecycle contract.'
Assert-Match $gate 'jdk\\bin\\java\.exe' 'Fabric 26.1.2 Minecraft must be bound to the installed bundled Java 25 runtime.'
Assert-Match $gate 'jdk21\\bin\\java\.exe' 'The same installed candidate must still contain the Java 21 sidecar for maintenance tracks.'
Assert-Match $gate 'EnumWindows' 'Visible Minecraft detection must enumerate real top-level Win32 windows rather than depend on Java Process.MainWindowTitle.'
Assert-Match $gate 'GetWindowThreadProcessId' 'Visible window evidence must bind the top-level window to its process.'
Assert-NotMatch $gate '\[uint32\]\$pid\s*=' 'Window enumeration must not shadow PowerShell''s read-only automatic $PID variable.'
Assert-Match $gate 'Get-BundledRuntimeVisibleWindow' 'Minecraft visibility must be tied to the installed bundled Java 25 runtime required by Fabric 26.1.2.'
Assert-Match $gate 'Get-BundledRuntimeProcessIds' 'The runClient gate must snapshot bundled-runtime process ids before launch so the Copperbench desktop cannot be mistaken for Minecraft.'
Assert-Match $gate 'Get-BundledRuntimeVisibleWindow \$runRuntimeBefore' 'Minecraft visibility must require a new bundled-runtime process after the real runClient click.'
Assert-NotMatch $gate "MainWindowTitle -match 'Minecraft'" 'The gate must not depend on an unstable Minecraft title string.'
Assert-Match $gate 'stableRunningSeconds=20' 'Interactive runClient must remain running through the 20-second stability window.'
Assert-Match $gate 'PostMessage.+0x0010' 'Minecraft must be closed through the normal WM_CLOSE window path.'
Assert-Match $gate 'gradleExitCode=\$runExitCode' 'Evidence must record the runClient Gradle exit code after normal close.'
Assert-Match $gate 'descriptorRemoved=\$true' 'Normal Copperbench close must remove the Desktop MCP descriptor.'
Assert-Match $gate 'fullStage15WindowsRegressionPassed' 'Final evidence must combine baseline and runClient lifecycle results.'
Assert-Match $gate 'previous Stage 15 Windows product-regression guest task is still running' 'The gate must refuse overlapping interactive acceptance tasks.'
Assert-Match $gate "workspace-' \+ \[guid\]::NewGuid" 'Each acceptance replay must use a unique disposable workspace so failed Gradle caches cannot contaminate the next run.'
Assert-Match $gate "windows-product-regression-clean-windows11\.json'\) -Force" 'The host must clear only stale stable-result files before starting a new acceptance task.'
Assert-Match $gate "windows-build-diagnostic\.stdout\.log'\) -Force" 'Each acceptance replay must clear stale direct-build stdout diagnostics before starting.'
Assert-Match $gate "windows-build-diagnostic\.stderr\.log'\) -Force" 'Each acceptance replay must clear stale direct-build stderr diagnostics before starting.'
Assert-NotMatch $gate 'Remove-Item -LiteralPath \$Root -Recurse' 'The host must not recursively delete prior failed acceptance workspaces that can contain locked Gradle state.'
Assert-Match $gate 'CollectExistingGuestTask' 'The gate must support collecting an already-running acceptance task without restarting it.'
Assert-Match $gate 'InspectExistingGuestTask' 'The gate must provide a read-only status probe for an already-running acceptance task.'
Assert-Match $gate 'lastTaskResult' 'The read-only status probe must expose scheduled-task completion state without restarting acceptance.'
Assert-Match $gate 'buildDiagnosticStdoutTail' 'The read-only status probe must surface the bounded direct-build diagnostic stdout tail.'
Assert-Match $gate 'buildDiagnosticStderrTail' 'The read-only status probe must surface the bounded direct-build diagnostic stderr tail.'
Assert-Match $gate 'latestWorkspace=\$workspaceProbe' 'The read-only status probe must expose bounded progress facts for the newest disposable workspace.'
Assert-Match $gate 'MainWindowHandle' 'The read-only status probe must expose candidate-process window identity without restarting acceptance.'
Assert-Match $gate 'StopFailedExistingGuestTask' 'The gate must provide a guarded way to stop a failed acceptance task that never reached stable-result finalization.'
Assert-Match $gate 'Refusing to stop a running acceptance task without failure evidence' 'The failed-task stop path must require failure evidence before stopping the scheduled task.'
Assert-Match $gate 'CleanupExistingGuestWindowsOnly' 'The gate must provide a normal-close cleanup path after a failed interactive acceptance run.'
Assert-Match $gate "cleanupOnly=true" 'Cleanup mode must be explicitly separated from acceptance evidence.'
Assert-Match $gate 'Set-Content -LiteralPath \$scriptPath -Value \$Body -Encoding Unicode' 'The Windows PowerShell guest task script must use a BOM-backed encoding so non-ASCII UI Automation names survive.'
Assert-Match $gate 'Remove-Item -LiteralPath \$descriptorPath -Force' 'The disposable workspace must not reuse a stale Desktop MCP descriptor copied from the preserved fixture.'
Assert-Match $gate "transientTopLevel = @\('\.gradle', 'build', 'run', '\.copperbench'\)" 'The disposable workspace must exclude locked Gradle/build/run/MCP transient state from the preserved fixture.'
Assert-NotMatch $gate "Call-Tool 'cancel_task'" 'The gate must not cancel runClient to fake a normal user close.'
Assert-NotMatch $gate 'Stop-Process' 'The gate must not kill Minecraft or Copperbench to fake normal close.'

Write-Output 'Stage 15 Windows product-regression gate contract passed.'
